import telebot
import requests
import base64
import os
import time
from flask import Flask
from threading import Thread

# --- CONFIG ---
TOKEN = os.getenv('TG_TOKEN') # Aapka Telegram Bot Token
OR_API_KEY = os.getenv('OR_API_KEY') # OpenRouter API Key

# Models
CHAT_MODEL = "google/gemini-2.0-flash-001" # Chat aur Vision ke liye
IMAGE_GEN_API = "https://image.pollinations.ai/prompt/" # Free & Fast Image Gen

bot = telebot.TeleBot(TOKEN, parse_mode="Markdown")
app = Flask('')

# --- WEB SERVER (For Render 24/7) ---
@app.route('/')
def home(): return "Multi-AI Bot is Running!"

def keep_alive():
    Thread(target=lambda: app.run(host='0.0.0.0', port=8080)).start()

# --- HELPERS ---
def generate_image(prompt):
    # Prompt ko URL-safe banana
    encoded_prompt = requests.utils.quote(prompt)
    image_url = f"{IMAGE_GEN_API}{encoded_prompt}"
    # Pollinations AI seed based on time for unique images
    seed = int(time.time())
    final_url = f"{image_url}?seed={seed}&width=1024&height=1024&nologo=true"
    return final_url

# --- BOT LOGIC ---

# 1. Start Command
@bot.message_handler(commands=['start'])
def start(message):
    welcome_text = (
        "👋 **Namaste! Main hoon aapka Multi-AI Assistant.**\n\n"
        "Main ye sab kar sakta hoon:\n"
        "💬 **Chat:** Bas kuch bhi puchhein.\n"
        "🖼️ **Vision:** Koi bhi photo bhejein, main use samajh loonga.\n"
        "🎨 **Imagine:** Likhein `/imagine [aapka prompt]` aur main image bana doonga.\n\n"
        "Bataiye, kya sewa karoon?"
    )
    bot.send_message(message.chat.id, welcome_text)

# 2. Image Generation Command (/imagine)
@bot.message_handler(commands=['imagine'])
def imagine(message):
    uid = message.from_user.id
    # Command ke baad wala text nikalna
    try:
        prompt = message.text.split(' ', 1)[1]
    except IndexError:
        bot.reply_to(message, "⚠️ Kripya `/imagine` ke baad apna prompt likhein.\nUdaharan: `/imagine a futuristic city with flying cars`")
        return

    # User ko loading message dikhana
    status_msg = bot.reply_to(message, f"🎨 _Imagining: {prompt}_...\nIsme 10-15 second lag sakte hain.")

    try:
        # Image generate karna
        img_url = generate_image(prompt)
        
        # Image bhejna
        bot.send_photo(message.chat.id, img_url, caption=f"✨ **Generated by Multi-AI**\nPrompt: `{prompt}`")
        
        # Loading message delete karna
        bot.delete_message(message.chat.id, status_msg.message_id)
        
    except Exception as e:
        bot.edit_message_text(f"❌ Error: Image generate nahi ho payi. ({str(e)})", chat_id=message.chat.id, message_id=status_msg.message_id)

# 3. Chat & Vision Logic (Text aur Photo dono handle karega)
@bot.message_handler(content_types=['text', 'photo'])
def handle_chat_and_vision(message):
    uid = message.from_user.id
    chat_id = message.chat.id
    
    # Agar text hai
    user_text = message.text or message.caption or "Analyze this image"
    
    # Agar user ne command likhi hai par galat formatting mein, toh ignore karein
    if user_text.startswith('/'): return

    # Gemini Loading state
    status = bot.reply_to(message, "🤔 _Thinking..._")

    img_b64 = None
    if message.content_type == 'photo':
        # Photo download karke Base64 mein badalna (Gemini Vision ke liye)
        file_info = bot.get_file(message.photo[-1].file_id)
        downloaded_file = bot.download_file(file_info.file_path)
        img_b64 = base64.b64encode(downloaded_file).decode('utf-8')

    # API Request structure
    headers = {"Authorization": f"Bearer {OR_API_KEY}", "Content-Type": "application/json"}
    
    content_list = [{"type": "text", "text": user_text}]
    if img_b64:
        content_list.append({"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{img_b64}"}})
    
    # System prompt taaki Gemini pro lage
    payload = {
        "model": CHAT_MODEL,
        "messages": [
            {"role": "system", "content": "You are a helpful, smart, and friendly AI assistant. You can chat, see images, and give advice. Reply in Hindi (using Latin script if needed) and use bold text for emphasis."},
            {"role": "user", "content": content_list}
        ]
    }

    try:
        # OpenRouter (Gemini) API Call
        r = requests.post("https://openrouter.ai/api/v1/chat/completions", headers=headers, json=payload, timeout=60)
        
        if r.status_code == 200:
            ai_reply = r.json()['choices'][0]['message']['content']
            # Jawab bhejna (Markdown support ke saath)
            bot.edit_message_text(ai_reply, chat_id=chat_id, message_id=status.message_id)
        else:
            bot.edit_message_text(f"❌ Gemini Error: {r.status_code}", chat_id=chat_id, message_id=status.message_id)
            
    except Exception as e:
        bot.edit_message_text(f"⚠️ Error: Connect nahi ho paya. ({str(e)})", chat_id=chat_id, message_id=status.message_id)

if __name__ == '__main__':
    keep_alive()
    print("Multi-AI Bot is ready!")
    bot.infinity_polling()
